# Generated by Django 4.1.5 on 2023-02-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=100)),
                ('Password', models.CharField(max_length=30)),
                ('Confirm_Password', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='login',
            name='pswrd',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
