# Generated by Django 4.1.5 on 2023-02-08 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_contact1_delete_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
