# Generated by Django 4.1.5 on 2023-03-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_ID', models.CharField(max_length=200)),
                ('Abnormal_short_term_variability', models.CharField(max_length=500)),
                ('Percentage_of_time_with_ALTV', models.CharField(max_length=500)),
                ('Mean_value_short_term', models.CharField(max_length=500)),
                ('Histogram_mean', models.CharField(max_length=500)),
                ('Prolongued_decelerations', models.CharField(max_length=500)),
                ('Histogram_median', models.CharField(max_length=500)),
                ('Accelerations', models.CharField(max_length=500)),
                ('Histogram_mode', models.CharField(max_length=500)),
                ('Mean_value_of_LTV', models.CharField(max_length=500)),
                ('Histogram_min', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='User_Details',
        ),
    ]
